### ISSUE TITLE
general question

### ISSUE THREAD

**Issue by gillyb** [jeresig/elasticsearch-orm#1]
Hey,

Is this library currently being used by you ?
I was wondering if it's in a stable state ?
Do you have a working example of this library in use in some other public repo ?
I want to use it, as it seems like a lightweight elasticsearch orm and good enough for my needs.

Thanks in advance,
Gilly.

**Comment by jeresig** [comment]
@gillyb Hello! Unfortunately I'm not using this library at the moment, not would I consider it to be in a stable state. Sorry!
